name: 'Lint and Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deps
        run: node common/scripts/install-run-rush.js install
      - name: Lint
        run: node common/scripts/install-run-rush.js danger-ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Typecheck
        run: node ../common/scripts/install-run-rushx.js typecheck
        working-directory: bemuse
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deps
        run: node common/scripts/install-run-rush.js install
      - name: Build
        run: node common/scripts/install-run-rush.js build --to-except bemuse
      - name: Test
        run: node ../common/scripts/install-run-rushx.js test
        working-directory: bemuse
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deps
        run: node common/scripts/install-run-rush.js install
      - name: Build
        run: node common/scripts/install-run-rush.js build --to-except bemuse
      - name: Test Packages
        run: node common/scripts/install-run-rush.js test --to-except bemuse
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
