on:
  push:
    branches:
      - master
name: Process TODO comments
jobs:
  collectTODO:
    name: Collect TODO
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Collect TODO
      uses: dtinth/todo-actions@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
